### ISSUE TITLE
update legend, get it from new server

### ISSUE THREAD

**Issue by sbsimo** [ITHACA-org/erds-web#14]
The legend below is still coming from the old server, please substitute it with the new server

![image](https://user-images.githubusercontent.com/828337/33383945-fb007506-d524-11e7-90fe-00e80dd764e1.png)

**Comment by sbsimo** [comment]
insert request from 
https://github.com/ITHACA-org/erds-web/blob/master/utils/legend_requests.txt

**Comment by CoSandu** [comment]
Hi Simo,
is this issue still open?
Ciao,
Consta

**Comment by sbsimo** [comment]
hey @CoSandu, still open

**Comment by sbsimo** [comment]
issue solved with #19
