### ISSUE TITLE
Warning regarding forecast alerts

### ISSUE THREAD

**Issue by paolamazzoglio** [ITHACA-org/erds-web#26]
Add an "under development" message (or something similar) near "Alert Forecast", in the Layers page.

![cattura](https://user-images.githubusercontent.com/44401784/47361616-b0a6d580-d6d2-11e8-97b6-b7eefb02bef5.JPG)

**Comment by sbsimo** [comment]
Per me ok.
@ppasq approvi?

**Comment by ppasq** [comment]
Ok.
